# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: containerhost1.fqdn.tld:5000/docker:latest
variables:
  DOCKER_DRIVER: overlay
  CI_REGISTRY_IMAGE: containerhost1.fqdn.tld:5000/docker:latest
services:
  - docker:dind

build-master:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

build:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master
